### ISSUE TITLE
node_redis problem

### ISSUE THREAD

**Issue by dhafer1** [Acrack/AckNotificationBundle#2]
Problem :node_redis: Deprecated: The HMSET command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.
 I  have this problem with server.js .
thanks

**Comment by Dens49** [comment]
When you use version 1.0.0 then userAction.js will try to store user.sessionId, which has to be part of the user object you send via websocket on loaded.
You probably looked at the README for the master branch, which doesn't mention the user.sessionId, because it has been removed in master branch [in this commit](https://github.com/Acrack/AckNotificationBundle/commit/3f4a71f5507680fe1c6e818fee1c9b556b823918#diff-623bca047f84583c2cdd4667750edd7f).

So either use branch master or make sure your client sends a sessionId.

**Comment by dhafer1** [comment]
thank you Dens49 you solved my problem
